### PR TITLE
PIP-69 Add deps vuln scan

### PR DESCRIPTION
**Pull request by milt**
[PIP-69] Use `nvd-clojure` to scan for vulnerable deps

[PIP-69]: https://yet.atlassian.net/browse/PIP-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by cliffcaseyyet — COMMENTED** [review]
Just two questions:
- What's the eviction policy on the NVD owasp cache? I didn't see anything explicit
- I pulled and ran nvd locally and obviously nothing SEVERE, but is there any actions behavior like a failure if there is?

**Comment by milt** [comment]
> What's the eviction policy on the NVD owasp cache? I didn't see anything explicit

Heh, a little weird. So you'll notice it is explicitly banned in the general deps cache (just above), then it gets its own cache of _just_ the owasp path (containing the db)

**Comment by milt** [comment]
The storage/eviction policy is a little more complicated. The github cache action _only ever saves_ on a pass, so if there is any vuln it won't save any updates it found that go-round. Not ideal, but not horrible. Unfortunately you can not currently change the DB directory in the tools.cli version of `nvd-clojure`.

**Comment by milt** [comment]
> I pulled and ran nvd locally and obviously nothing SEVERE, but is there any actions behavior like a failure if there is?

`nvd-clojure` returns a nonzero exit status (by design) on any vuln, yeah

**Comment by milt** [comment]
You can see it failing (doing its job) here: https://github.com/yetanalytics/xapipe/runs/4523404235?check_suite_focus=true

**Comment by cliffcaseyyet** [comment]
> You can see it failing (doing its job) here: https://github.com/yetanalytics/xapipe/runs/4523404235?check_suite_focus=true

Cool, that seems great.

**Review by cliffcaseyyet — APPROVED** [review]

**Pull request merged**
